name: Fetch movie.json every hour

on:
  push:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

permissions: write-all

jobs:
  fetch-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Fetch movie data (with retries)
        run: |
          curl -s --max-time 300 --retry 3 --retry-delay 10 https://movie.timie.workers.dev/ -o movie.json

      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add movie.json
          git diff --cached --quiet || (git commit -m "Update movie.json [auto]" && git push)

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 1
